# Generated by Django 6.0.6 on 2026-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DEAL', 'Deal'), ('LEAD', 'Lead'), ('CUSTOMER', 'Customer'), ('TASK', 'Task'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
