# Generated by Django 6.0.6 on 2026-06-17 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CUSTOMER_CREATED', 'Customer Created'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_STAGE_CHANGED', 'Deal Stage Changed'), ('TASK_CREATED', 'Task Created'), ('TASK_COMPLETED', 'Task Completed')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
