apiVersion: v1

kind: ConfigMap

metadata:
  name: crm-config
  namespace: crm

data:

  DEBUG: "False"

  DB_NAME: "crm_db"

  DB_HOST: "postgres-service"

  DB_PORT: "5432"

  ALLOWED_HOSTS: "*"

  CORS_ALLOW_ALL_ORIGINS: "True"