apiVersion: v1

kind: Secret

metadata:

  name: crm-secret

  namespace: crm

type: Opaque

stringData:

  SECRET_KEY: "django-insecure-x@^!udf%lqv!s1ta3^8ba20%m4e6q+^px)u+lc6+ux310kyr-p"

  DB_PASSWORD: "667254"